const constants = {
    ADD_ERROR: 'ADD_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_FACULTY: 'ADD_FACULTY',
    GET_FACULTIES: 'GET_FACULTIES',
    REMOVE_FACULTY: 'REMOVE_FACULTY',
    UPDATE_FACULTY: 'UPDATE_FACULTY',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    GET_DEPARTMENTS: 'GET_DEPARTMENTS',
    REMOVE_DEPARTMENT: 'REMOVE_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    GRID_STATE_CHANGE_ACTION: 'GRID_STATE_CHANGE'
}

export default constants