const constants = {
    ADD_ERROR: 'ADD_ERROR',
    REMOVE_ERROR: 'REMOVE_ERROR',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    ADD_FACULTY: 'ADD_FACULTY',
    GET_FACULTIES: 'GET_FACULTIES',
    REMOVE_FACULTY: 'REMOVE_FACULTY',
    UPDATE_FACULTY: 'UPDATE_FACULTY',
    ADD_DEPARTMENT: 'ADD_DEPARTMENT',
    GET_DEPARTMENTS: 'GET_DEPARTMENTS',
    REMOVE_DEPARTMENT: 'REMOVE_DEPARTMENT',
    UPDATE_DEPARTMENT: 'UPDATE_DEPARTMENT',
    ADD_ELECTION: 'ADD_ELECTION',
    GET_ELECTIONS: 'GET_ELECTIONS',
    REMOVE_ELECTION: 'REMOVE_ELECTION',
    UPDATE_ELECTION: 'UPDATE_ELECTION',
    FACULTY_GRID_STATE_CHANGE_ACTION: 'FACULTY_GRID_STATE_CHANGE_ACTION',
    DEPARTMENT_GRID_STATE_CHANGE_ACTION: 'DEPARTMENT_GRID_STATE_CHANGE_ACTION',
    ELECTION_GRID_STATE_CHANGE_ACTION: 'ELECTION_GRID_STATE_CHANGE_ACTION',
}

export default constants